
{'is_insertable_into': 'YES',
 'commit_action': None,
 'user_defined_type_name': None,
 'table_type': 'BASE TABLE',
 'table_name': 'pg_type',
 'is_typed': 'NO',
 'self_referencing_column_name': None,
 'reference_generation': None,
 'table_catalog': 'postgres',
 'user_defined_type_catalog': None,
 'table_schema': 'pg_catalog',
 'user_defined_type_schema': None}

{'table_catalog': 'postgres',
 'reference_generation': None,
 'commit_action': None,
 'user_defined_type_name': None,
 'is_typed': 'NO',
 'self_referencing_column_name': None,
 'table_name': 'pg_attrdef',
 'table_schema': 'pg_catalog',
 'is_insertable_into': 'YES',
 'table_type': 'BASE TABLE',
 'user_defined_type_schema': None,
 'user_defined_type_catalog': None}

{'table_catalog': 'postgres',
 'reference_generation': None,
 'commit_action': None,
 'user_defined_type_name': None,
 'is_typed': 'NO',
 'self_referencing_column_name': None,
 'table_name': 'sql_implementation_info',
 'table_schema': 'information_schema',
 'is_insertable_into': 'YES',
 'table_type': 'BASE TABLE',
 'user_defined_type_schema': None,
 'user_defined_type_catalog': None}

{'table_catalog': 'postgres',
 'reference_generation': None,
 'commit_action': None,
 'user_defined_type_name': None,
 'is_typed': 'NO',
 'self_referencing_column_name': None,
 'table_name': 'pg_am',
 'table_schema': 'pg_catalog',
 'is_insertable_into': 'YES',
 'table_type': 'BASE TABLE',
 'user_defined_type_schema': None,
 'user_defined_type_catalog': None}

{'table_catalog': 'postgres',
 'reference_generation': None,
 'commit_action': None,
 'user_defined_type_name': None,
 'is_typed': 'NO',
 'self_referencing_column_name': None,
 'table_name': 'pg_db_role_setting',
 'table_schema': 'pg_catalog',
 'is_insertable_into': 'YES',
 'table_type': 'BASE TABLE',
 'user_defined_type_schema': None,
 'user_defined_type_catalog': None}

{'table_catalog': 'postgres',
 'reference_generation': None,
 'commit_action': None,
 'user_defined_type_name': None,
 'is_typed': 'NO',
 'self_referencing_column_name': None,
 'table_name': 'sql_features',
 'table_schema': 'information_schema',
 'is_insertable_into': 'YES',
 'table_type': 'BASE TABLE',
 'user_defined_type_schema': None,
 'user_defined_type_catalog': None}
